#ifndef _KERNEL_KEYS_H_
#define _KERNEL_KEYS_H_

#include "kernel.h"

enum _keycodes
{
	KEY_UNKNOWN, KEY_ESC, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0,
	KEY_MINUS, KEY_EQUAL, KEY_BACKSPACE, KEY_TAB, KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T,
	KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P, KEY_LEFTBRACKET, KEY_RIGHTBRACKET, KEY_ENTER,
	KEY_LEFTCTRL, KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L,
	KEY_SEMICOLON, KEY_SINGLEQUOTE, KEY_BACKTICK, KEY_LEFTSHIFT, KEY_BACKSLASH,
	KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M, KEY_COMMA, KEY_PERIOD, KEY_SLASH,
	KEY_RIGHTSHIFT, KEY_ASTERISK, KEY_LEFTALT, KEY_SPACE, KEY_CAPSLOCK, KEY_F1,
	KEY_F2, KEY_F3, KEY_F4,	KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_F10, KEY_NUMLOCK,
	KEY_SCRLOCK, KEY_K7, KEY_K8, KEY_K9, KEY_KMINUS, KEY_K4, KEY_K5, KEY_K6, KEY_KPLUS,
	KEY_K1, KEY_K2, KEY_K3, KEY_K0, KEY_KPERIOD, KEY_F11, KEY_F12, KEY_KENTER, KEY_RIGHTCTRL,
	KEY_RIGHTALT, KEY_HOME, KEY_CURSORUP, KEY_PAGEUP, KEY_CURSORLEFT, KEY_CURSORRIGHT,
	KEY_END, KEY_CURSORDOWN, KEY_PAGEDOWN, KEY_INSERT, KEY_DELETE, KEY_LEFTGUI,
	KEY_RIGHTGUI, KEY_APPS, KEY_PRINTSCREEN, KEY_PAUSE, KEY_KASTERISK, KEY_WWWSEARCH, KEY_MMPREV,
	KEY_WWWFAV, KEY_WWWREFRESH, KEY_MMVOLDOWN, KEY_MMMUTE, KEY_WWWSTOP, KEY_MMCALC, KEY_WWWFORWARD,
	KEY_MMVOLUP, KEY_MMPAUSE, KEY_ACPIPOWER, KEY_WWWBACK, KEY_WWWHOME, KEY_MMSTOP, KEY_ACPISLEEP,
	KEY_MMMYCOMP, KEY_MMEMAIL, KEY_KSLASH, KEY_MMNEXT, KEY_MMMEDIA, KEY_ACPIWAKE, KEY_COUNT
};

typedef u8 vkey_t;

#endif